const { IntegrationSetting, Order, Customer } = require("../models");
const { decrypt } = require("./encryption");

// Meta Cloud API (WhatsApp Business) credentials — same DB-first pattern as
// Shiprocket/Razorpay (see utils/shiprocket.js, utils/razorpay.js): stored in
// IntegrationSettings under integrationKey "whatsapp", admin-managed from
// Settings > Integrations > WhatsApp (see adminIntegrationSettingsController.js,
// which already handles the generic get/update).
//
// Shape stored in IntegrationSettings.config:
//   { accessToken(encrypted), phoneNumberId, businessAccountId, webhookVerifyToken(encrypted) }
//
// Below: sendTemplateMessage (the one Graph API call every message goes
// through — same shared-entry-point role as utils/email.js's sendEmail),
// order-status wrappers (sendOrderConfirmedWhatsApp/
// sendOrderDispatchedWhatsApp/sendOrderDeliveredWhatsApp — see
// whatsappSent on models/Order.js for the send-once guard, and the trigger
// points alongside utils/email.js's equivalents in controllers/
// orderController.js, checkoutController.js, webhookController.js, and
// utils/shiprocket.js), and sendOtpWhatsApp (used by utils/otpProviders/
// whatsapp.js as the "whatsapp" OTP_PROVIDER option).
const INTEGRATION_KEY = "whatsapp";
const GRAPH_API_VERSION = "v21.0";

// Template names as approved in Meta WhatsApp Manager (Business Settings >
// Message Templates) — see memory/whatsapp_integration_architecture.md for
// the exact drafts submitted and their approval status. If Meta requires a
// different name/wording during review, update these constants (and the
// component shapes below, if the approved structure differs) rather than
// the callers.
const TEMPLATES = {
  orderConfirmed: "order_confirmed",
  orderDispatched: "order_dispatched",
  orderDelivered: "order_delivered",
  // Meta's built-in Authentication category — whatever name is actually
  // approved for it (Authentication templates are created/named separately
  // from Utility ones in WhatsApp Manager, commonly "otp" or
  // "verification_code"). Update once known.
  otp: "otp_verification",
};
const TEMPLATE_LANGUAGE = "en_US";

// The exact drafts to submit for Meta review (WhatsApp Manager > Account
// Tools > Message Templates, or via submitAllTemplates()/scripts/
// submitWhatsappTemplates.js below) — kept here so the submitted wording
// and the constants/component shapes the senders above assume stay in
// one place. See memory/whatsapp_integration_architecture.md for
// submission/approval status.
const TEMPLATE_DRAFTS = [
  {
    name: TEMPLATES.orderConfirmed,
    category: "UTILITY",
    components: [
      {
        type: "BODY",
        text: "Hi {{1}}, your Sehat Potli order #{{2}} has been confirmed! Total: ₹{{3}}. We'll notify you once it's on its way. Thank you for shopping with us! 🌰",
        example: { body_text: [["Priya", "ORD-1234567890", "1,280"]] },
      },
    ],
  },
  {
    name: TEMPLATES.orderDispatched,
    category: "UTILITY",
    components: [
      {
        type: "BODY",
        text: "Good news {{1}}! Your order #{{2}} has been dispatched via {{3}} and is on its way. Estimated delivery: {{4}}. Track here: {{5}}",
        example: {
          body_text: [["Priya", "ORD-1234567890", "Delhivery", "31 Aug 2026", "https://sehatpotli.in/account/orders/abc123"]],
        },
      },
    ],
  },
  {
    name: TEMPLATES.orderDelivered,
    category: "UTILITY",
    components: [
      {
        type: "BODY",
        text: "Hi {{1}}, your order #{{2}} has been delivered! We hope you enjoy your Sehat Potli goodies. If you loved it, we'd appreciate a review! 🌟",
        example: { body_text: [["Priya", "ORD-1234567890"]] },
      },
    ],
  },
  {
    // Meta's built-in Authentication category — wording is generated by
    // Meta itself (not free text like the Utility templates above), per
    // their one-time-passcode format. add_security_recommendation appends
    // their standard "don't share this code" line; code_expiration_minutes
    // matches OTP_TTL_MS in controllers/mobileVerificationController.js (10
    // minutes); the OTP button gives the customer a one-tap "copy code"
    // action, matching sendOtpWhatsApp()'s component shape above.
    name: TEMPLATES.otp,
    category: "AUTHENTICATION",
    components: [
      { type: "BODY", add_security_recommendation: true },
      { type: "FOOTER", code_expiration_minutes: 10 },
      { type: "BUTTONS", buttons: [{ type: "OTP", otp_type: "COPY_CODE" }] },
    ],
  },
];

async function getConfig() {
  const setting = await IntegrationSetting.findOne({ where: { integrationKey: INTEGRATION_KEY } });
  return setting?.config || {};
}

// No .env fallback, same reasoning as Shiprocket's getWebhookSecret — this is
// a brand-new integration with nothing to migrate from, so an unconfigured
// webhook should fail closed rather than silently accept anything.
async function getWebhookVerifyToken() {
  const config = await getConfig();
  if (!config.webhookVerifyToken) {
    throw new Error(
      "WhatsApp webhook verify token is not configured — set it up from the admin panel (Settings > Integrations > WhatsApp)",
    );
  }
  return decrypt(config.webhookVerifyToken);
}

async function getCredentials() {
  const config = await getConfig();
  if (!config.accessToken || !config.phoneNumberId) {
    throw new Error(
      "WhatsApp credentials are not configured — set them up from the admin panel (Settings > Integrations > WhatsApp)",
    );
  }
  return {
    accessToken: decrypt(config.accessToken),
    phoneNumberId: config.phoneNumberId,
    businessAccountId: config.businessAccountId || null,
  };
}

// Meta's Cloud API wants the recipient as a plain country-code-prefixed
// number, no "+", no spaces (e.g. "919876543210") — same convention
// utils/otpProviders/msg91.js already uses for SMS. Every phone number in
// this codebase (Customer.mobileNumber, Order.shippingPhone) is stored as a
// bare 10-digit Indian number, so "91" is hardcoded here rather than made
// configurable — same assumption the rest of the checkout flow already
// makes (PINCODE_REGEX, mobile validation, etc. are all India-only).
function toWhatsappPhone(mobileNumber) {
  const digits = String(mobileNumber || "").replace(/\D/g, "");
  if (digits.length !== 10) {
    throw new Error(`Invalid mobile number for WhatsApp send: "${mobileNumber}"`);
  }
  return `91${digits}`;
}

// The one function every WhatsApp send goes through — POSTs to Meta's
// Cloud API (POST /{phone-number-id}/messages), same shared-entry-point
// role as utils/email.js's sendEmail(). Throws on failure (mirrors
// sendEmail, not the OTP providers) — callers that shouldn't let a WhatsApp
// error interrupt their own flow are expected to catch it themselves, same
// convention as sendOrderConfirmedEmail() etc. below already follow.
async function sendTemplateMessage(toPhoneNumber, templateName, languageCode, components) {
  const { accessToken, phoneNumberId } = await getCredentials();
  const to = toWhatsappPhone(toPhoneNumber);

  const res = await fetch(`https://graph.facebook.com/${GRAPH_API_VERSION}/${phoneNumberId}/messages`, {
    method: "POST",
    headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      messaging_product: "whatsapp",
      to,
      type: "template",
      template: {
        name: templateName,
        language: { code: languageCode || TEMPLATE_LANGUAGE },
        components,
      },
    }),
  });

  const data = await res.json().catch(() => ({}));
  if (!res.ok) {
    // Meta's error shape: { error: { message, type, code, error_subcode, fbtrace_id } }
    throw new Error(data?.error?.message || `WhatsApp send failed (${res.status})`);
  }
  return data;
}

function formatCurrencyINR(amount) {
  return `₹${Number(amount || 0).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;
}

function formatDateShort(date) {
  if (!date) return "soon";
  return new Date(date).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" });
}

const orderIncludesForWhatsapp = [{ model: Customer, attributes: ["id", "name"] }];

// Sends the "Order Confirmed" WhatsApp template — checks/sets
// whatsappSent.confirmed itself so a duplicate trigger never double-sends,
// same contract as sendOrderConfirmedEmail() in utils/email.js. Never
// throws: every failure is logged and returned as { success, error } so
// callers can fire this without their own try/catch.
async function sendOrderConfirmedWhatsApp(orderId) {
  const order = await Order.findByPk(orderId, { include: orderIncludesForWhatsapp });
  if (!order) return { success: false, error: "Order not found" };
  if (order.whatsappSent?.confirmed) return { success: true, skipped: true };

  try {
    if (!order.shippingPhone) throw new Error("Order has no shipping phone on file");
    await sendTemplateMessage(order.shippingPhone, TEMPLATES.orderConfirmed, TEMPLATE_LANGUAGE, [
      {
        type: "body",
        parameters: [
          { type: "text", text: order.Customer?.name || order.shippingName || "there" },
          { type: "text", text: order.orderNumber },
          { type: "text", text: formatCurrencyINR(order.total).replace("₹", "") },
        ],
      },
    ]);
    await order.update({ whatsappSent: { ...(order.whatsappSent || {}), confirmed: true } });
    console.log(`WhatsApp: order-confirmed sent for order ${order.orderNumber}`);
    return { success: true };
  } catch (err) {
    console.error(`WhatsApp: failed to send order-confirmed message for order ${order.orderNumber}: ${err.message}`);
    return { success: false, error: err.message };
  }
}

// Sends the "Order Dispatched" WhatsApp template — fires at the same
// trigger point as sendOrderPackedEmail (label generation, or the
// pickup-scan webhook — see utils/shiprocket.js), once courierName/
// estimatedDeliveryDate are set on the order. Same never-throws,
// flag-guarded contract as above.
async function sendOrderDispatchedWhatsApp(orderId) {
  const order = await Order.findByPk(orderId, { include: orderIncludesForWhatsapp });
  if (!order) return { success: false, error: "Order not found" };
  if (order.whatsappSent?.dispatched) return { success: true, skipped: true };

  try {
    if (!order.shippingPhone) throw new Error("Order has no shipping phone on file");
    const trackingUrl = `${process.env.STORE_FRONT_URL || "https://sehatpotli.in"}/account/orders/${order.id}`;
    await sendTemplateMessage(order.shippingPhone, TEMPLATES.orderDispatched, TEMPLATE_LANGUAGE, [
      {
        type: "body",
        parameters: [
          { type: "text", text: order.Customer?.name || order.shippingName || "there" },
          { type: "text", text: order.orderNumber },
          { type: "text", text: order.courierName || "our courier partner" },
          { type: "text", text: formatDateShort(order.estimatedDeliveryDate) },
          { type: "text", text: trackingUrl },
        ],
      },
    ]);
    await order.update({ whatsappSent: { ...(order.whatsappSent || {}), dispatched: true } });
    console.log(`WhatsApp: order-dispatched sent for order ${order.orderNumber}`);
    return { success: true };
  } catch (err) {
    console.error(`WhatsApp: failed to send order-dispatched message for order ${order.orderNumber}: ${err.message}`);
    return { success: false, error: err.message };
  }
}

// Sends the "Order Delivered" WhatsApp template — fires at the same
// trigger point as sendOrderDeliveredEmail (Shiprocket status webhook).
// Same never-throws, flag-guarded contract as above.
async function sendOrderDeliveredWhatsApp(orderId) {
  const order = await Order.findByPk(orderId, { include: orderIncludesForWhatsapp });
  if (!order) return { success: false, error: "Order not found" };
  if (order.whatsappSent?.delivered) return { success: true, skipped: true };

  try {
    if (!order.shippingPhone) throw new Error("Order has no shipping phone on file");
    await sendTemplateMessage(order.shippingPhone, TEMPLATES.orderDelivered, TEMPLATE_LANGUAGE, [
      {
        type: "body",
        parameters: [
          { type: "text", text: order.Customer?.name || order.shippingName || "there" },
          { type: "text", text: order.orderNumber },
        ],
      },
    ]);
    await order.update({ whatsappSent: { ...(order.whatsappSent || {}), delivered: true } });
    console.log(`WhatsApp: order-delivered sent for order ${order.orderNumber}`);
    return { success: true };
  } catch (err) {
    console.error(`WhatsApp: failed to send order-delivered message for order ${order.orderNumber}: ${err.message}`);
    return { success: false, error: err.message };
  }
}

// Sends the OTP via Meta's Authentication template category. Unlike the
// order-status senders above, this THROWS on failure rather than
// swallowing it — it's called from utils/otpProviders/whatsapp.js, which
// (like every other OTP provider — see msg91.js) is expected to throw so
// mobileVerificationController.js's sendOtp surfaces a real error to the
// customer instead of silently pretending an OTP was sent.
//
// Body shape follows Meta's default suggested Authentication template
// (one body parameter — the code — plus a "copy code" quick-reply button
// carrying the same code) — this is what WhatsApp Manager scaffolds by
// default when creating an Authentication-category template. If the
// actually-approved template omits the button (or uses a "one-tap
// autofill" url button instead), update the `components` shape here to
// match — Meta rejects a send whose components don't match the approved
// template's own structure.
async function sendOtpWhatsApp(phoneNumber, otpCode) {
  return sendTemplateMessage(phoneNumber, TEMPLATES.otp, TEMPLATE_LANGUAGE, [
    { type: "body", parameters: [{ type: "text", text: String(otpCode) }] },
    {
      type: "button",
      sub_type: "copy_code",
      index: "0",
      parameters: [{ type: "coupon_code", coupon_code: String(otpCode) }],
    },
  ]);
}

// ---------------------------------------------------------------------------
// Template management (Meta WhatsApp Manager's Message Templates, driven via
// API instead of the manual UI) — not called from anywhere in the request
// path above; only from scripts/submitWhatsappTemplates.js, a deliberately
// standalone, manually-run script (never wired into app startup or any
// route) since submitting content for review against a real Meta Business
// Account is a one-off admin action, not something the app should ever do
// on its own.
// ---------------------------------------------------------------------------

// POST /{waba-id}/message_templates for each draft in TEMPLATE_DRAFTS.
// Meta queues each one for review (typically minutes to ~24h) rather than
// approving synchronously — see listTemplateStatuses() below to check back.
// Does NOT throw on an individual template's failure (e.g. it already
// exists, or Meta rejects the draft outright) — collects every result so
// one bad draft doesn't stop the rest from submitting.
async function submitAllTemplates() {
  const { accessToken, businessAccountId } = await getCredentials();
  if (!businessAccountId) {
    throw new Error("WhatsApp Business Account ID is not configured — set it from Settings > Integrations > WhatsApp");
  }

  const results = [];
  for (const draft of TEMPLATE_DRAFTS) {
    try {
      const res = await fetch(`https://graph.facebook.com/${GRAPH_API_VERSION}/${businessAccountId}/message_templates`, {
        method: "POST",
        headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" },
        body: JSON.stringify({
          name: draft.name,
          language: TEMPLATE_LANGUAGE,
          category: draft.category,
          components: draft.components,
        }),
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        results.push({ name: draft.name, success: false, error: data?.error?.message || `HTTP ${res.status}` });
      } else {
        results.push({ name: draft.name, success: true, id: data.id, status: data.status, category: data.category });
      }
    } catch (err) {
      results.push({ name: draft.name, success: false, error: err.message });
    }
  }
  return results;
}

// GET /{waba-id}/message_templates — current review status of every
// template on the account (not just the 4 this project submitted), so a
// re-run after Meta's review window shows APPROVED/REJECTED/PENDING per
// template without needing the WhatsApp Manager UI open.
async function listTemplateStatuses() {
  const { accessToken, businessAccountId } = await getCredentials();
  if (!businessAccountId) {
    throw new Error("WhatsApp Business Account ID is not configured — set it from Settings > Integrations > WhatsApp");
  }

  const res = await fetch(
    `https://graph.facebook.com/${GRAPH_API_VERSION}/${businessAccountId}/message_templates?fields=name,status,category,language,rejected_reason`,
    { headers: { Authorization: `Bearer ${accessToken}` } },
  );
  const data = await res.json().catch(() => ({}));
  if (!res.ok) {
    throw new Error(data?.error?.message || `HTTP ${res.status}`);
  }
  return data.data || [];
}

module.exports = {
  getWebhookVerifyToken,
  getCredentials,
  sendTemplateMessage,
  sendOrderConfirmedWhatsApp,
  sendOrderDispatchedWhatsApp,
  sendOrderDeliveredWhatsApp,
  sendOtpWhatsApp,
  submitAllTemplates,
  listTemplateStatuses,
  TEMPLATE_DRAFTS,
};
